/* Auto-generated by genmsg_cpp for file /home/samer/code_release/hitl-slam/vector_slam_msgs/msg/CobotAnomalyMonitorRectangleMsg.msg */
#ifndef VECTOR_SLAM_MSGS_MESSAGE_COBOTANOMALYMONITORRECTANGLEMSG_H
#define VECTOR_SLAM_MSGS_MESSAGE_COBOTANOMALYMONITORRECTANGLEMSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace vector_slam_msgs
{
template <class ContainerAllocator>
struct CobotAnomalyMonitorRectangleMsg_ {
  typedef CobotAnomalyMonitorRectangleMsg_<ContainerAllocator> Type;

  CobotAnomalyMonitorRectangleMsg_()
  : header()
  , lowerLeft()
  , upperRight()
  , anomaly(0.0)
  , mean()
  , var()
  , nSamples(0)
  {
  }

  CobotAnomalyMonitorRectangleMsg_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , lowerLeft(_alloc)
  , upperRight(_alloc)
  , anomaly(0.0)
  , mean(_alloc)
  , var(_alloc)
  , nSamples(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _lowerLeft_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  lowerLeft;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _upperRight_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  upperRight;

  typedef float _anomaly_type;
  float anomaly;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _mean_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  mean;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _var_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  var;

  typedef int32_t _nSamples_type;
  int32_t nSamples;


  typedef boost::shared_ptr< ::vector_slam_msgs::CobotAnomalyMonitorRectangleMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vector_slam_msgs::CobotAnomalyMonitorRectangleMsg_<ContainerAllocator>  const> ConstPtr;
}; // struct CobotAnomalyMonitorRectangleMsg
typedef  ::vector_slam_msgs::CobotAnomalyMonitorRectangleMsg_<std::allocator<void> > CobotAnomalyMonitorRectangleMsg;

typedef boost::shared_ptr< ::vector_slam_msgs::CobotAnomalyMonitorRectangleMsg> CobotAnomalyMonitorRectangleMsgPtr;
typedef boost::shared_ptr< ::vector_slam_msgs::CobotAnomalyMonitorRectangleMsg const> CobotAnomalyMonitorRectangleMsgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::vector_slam_msgs::CobotAnomalyMonitorRectangleMsg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::vector_slam_msgs::CobotAnomalyMonitorRectangleMsg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace vector_slam_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vector_slam_msgs::CobotAnomalyMonitorRectangleMsg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vector_slam_msgs::CobotAnomalyMonitorRectangleMsg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vector_slam_msgs::CobotAnomalyMonitorRectangleMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fe19f06a5b73d3d62843bf6bc9336729";
  }

  static const char* value(const  ::vector_slam_msgs::CobotAnomalyMonitorRectangleMsg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xfe19f06a5b73d3d6ULL;
  static const uint64_t static_value2 = 0x2843bf6bc9336729ULL;
};

template<class ContainerAllocator>
struct DataType< ::vector_slam_msgs::CobotAnomalyMonitorRectangleMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vector_slam_msgs/CobotAnomalyMonitorRectangleMsg";
  }

  static const char* value(const  ::vector_slam_msgs::CobotAnomalyMonitorRectangleMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vector_slam_msgs::CobotAnomalyMonitorRectangleMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
float32[] lowerLeft\n\
float32[] upperRight\n\
float32 anomaly\n\
float32[] mean\n\
float32[] var\n\
int32 nSamples\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::vector_slam_msgs::CobotAnomalyMonitorRectangleMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::vector_slam_msgs::CobotAnomalyMonitorRectangleMsg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::vector_slam_msgs::CobotAnomalyMonitorRectangleMsg_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vector_slam_msgs::CobotAnomalyMonitorRectangleMsg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.lowerLeft);
    stream.next(m.upperRight);
    stream.next(m.anomaly);
    stream.next(m.mean);
    stream.next(m.var);
    stream.next(m.nSamples);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CobotAnomalyMonitorRectangleMsg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vector_slam_msgs::CobotAnomalyMonitorRectangleMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::vector_slam_msgs::CobotAnomalyMonitorRectangleMsg_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lowerLeft[]" << std::endl;
    for (size_t i = 0; i < v.lowerLeft.size(); ++i)
    {
      s << indent << "  lowerLeft[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.lowerLeft[i]);
    }
    s << indent << "upperRight[]" << std::endl;
    for (size_t i = 0; i < v.upperRight.size(); ++i)
    {
      s << indent << "  upperRight[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.upperRight[i]);
    }
    s << indent << "anomaly: ";
    Printer<float>::stream(s, indent + "  ", v.anomaly);
    s << indent << "mean[]" << std::endl;
    for (size_t i = 0; i < v.mean.size(); ++i)
    {
      s << indent << "  mean[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.mean[i]);
    }
    s << indent << "var[]" << std::endl;
    for (size_t i = 0; i < v.var.size(); ++i)
    {
      s << indent << "  var[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.var[i]);
    }
    s << indent << "nSamples: ";
    Printer<int32_t>::stream(s, indent + "  ", v.nSamples);
  }
};


} // namespace message_operations
} // namespace ros

#endif // VECTOR_SLAM_MSGS_MESSAGE_COBOTANOMALYMONITORRECTANGLEMSG_H

