/* Auto-generated by genmsg_cpp for file /home/samer/code_release/hitl-slam/vector_slam_msgs/msg/LidarDisplayMsg.msg */
#ifndef VECTOR_SLAM_MSGS_MESSAGE_LIDARDISPLAYMSG_H
#define VECTOR_SLAM_MSGS_MESSAGE_LIDARDISPLAYMSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace vector_slam_msgs
{
template <class ContainerAllocator>
struct LidarDisplayMsg_ {
  typedef LidarDisplayMsg_<ContainerAllocator> Type;

  LidarDisplayMsg_()
  : timestamp(0.0)
  , robotLocX(0.0)
  , robotLocY(0.0)
  , robotAngle(0.0)
  , windowSize(0.0)
  , lines_p1x()
  , lines_p1y()
  , lines_p2x()
  , lines_p2y()
  , lines_col()
  , points_x()
  , points_y()
  , points_col()
  , circles_x()
  , circles_y()
  , circles_col()
  , text_x()
  , text_y()
  , text_col()
  , text()
  , text_height()
  , text_in_window_coords()
  {
  }

  LidarDisplayMsg_(const ContainerAllocator& _alloc)
  : timestamp(0.0)
  , robotLocX(0.0)
  , robotLocY(0.0)
  , robotAngle(0.0)
  , windowSize(0.0)
  , lines_p1x(_alloc)
  , lines_p1y(_alloc)
  , lines_p2x(_alloc)
  , lines_p2y(_alloc)
  , lines_col(_alloc)
  , points_x(_alloc)
  , points_y(_alloc)
  , points_col(_alloc)
  , circles_x(_alloc)
  , circles_y(_alloc)
  , circles_col(_alloc)
  , text_x(_alloc)
  , text_y(_alloc)
  , text_col(_alloc)
  , text(_alloc)
  , text_height(_alloc)
  , text_in_window_coords(_alloc)
  {
  }

  typedef double _timestamp_type;
  double timestamp;

  typedef double _robotLocX_type;
  double robotLocX;

  typedef double _robotLocY_type;
  double robotLocY;

  typedef double _robotAngle_type;
  double robotAngle;

  typedef double _windowSize_type;
  double windowSize;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _lines_p1x_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  lines_p1x;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _lines_p1y_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  lines_p1y;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _lines_p2x_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  lines_p2x;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _lines_p2y_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  lines_p2y;

  typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _lines_col_type;
  std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  lines_col;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _points_x_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  points_x;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _points_y_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  points_y;

  typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _points_col_type;
  std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  points_col;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _circles_x_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  circles_x;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _circles_y_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  circles_y;

  typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _circles_col_type;
  std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  circles_col;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _text_x_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  text_x;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _text_y_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  text_y;

  typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _text_col_type;
  std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  text_col;

  typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _text_type;
  std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  text;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _text_height_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  text_height;

  typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _text_in_window_coords_type;
  std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  text_in_window_coords;


  typedef boost::shared_ptr< ::vector_slam_msgs::LidarDisplayMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vector_slam_msgs::LidarDisplayMsg_<ContainerAllocator>  const> ConstPtr;
}; // struct LidarDisplayMsg
typedef  ::vector_slam_msgs::LidarDisplayMsg_<std::allocator<void> > LidarDisplayMsg;

typedef boost::shared_ptr< ::vector_slam_msgs::LidarDisplayMsg> LidarDisplayMsgPtr;
typedef boost::shared_ptr< ::vector_slam_msgs::LidarDisplayMsg const> LidarDisplayMsgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::vector_slam_msgs::LidarDisplayMsg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::vector_slam_msgs::LidarDisplayMsg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace vector_slam_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vector_slam_msgs::LidarDisplayMsg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vector_slam_msgs::LidarDisplayMsg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vector_slam_msgs::LidarDisplayMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cfcbc214eeeee7ce5b600cc5a2a37857";
  }

  static const char* value(const  ::vector_slam_msgs::LidarDisplayMsg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xcfcbc214eeeee7ceULL;
  static const uint64_t static_value2 = 0x5b600cc5a2a37857ULL;
};

template<class ContainerAllocator>
struct DataType< ::vector_slam_msgs::LidarDisplayMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vector_slam_msgs/LidarDisplayMsg";
  }

  static const char* value(const  ::vector_slam_msgs::LidarDisplayMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vector_slam_msgs::LidarDisplayMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 timestamp\n\
\n\
float64 robotLocX\n\
float64 robotLocY\n\
float64 robotAngle\n\
\n\
float64 windowSize\n\
\n\
float32[] lines_p1x\n\
float32[] lines_p1y\n\
float32[] lines_p2x\n\
float32[] lines_p2y\n\
uint32[]   lines_col\n\
\n\
float32[] points_x\n\
float32[] points_y\n\
uint32[]   points_col\n\
\n\
float32[] circles_x\n\
float32[] circles_y\n\
uint32[]   circles_col\n\
\n\
float32[] text_x\n\
float32[] text_y\n\
uint32[] text_col\n\
string[] text\n\
float32[] text_height\n\
bool[] text_in_window_coords\n\
\n\
";
  }

  static const char* value(const  ::vector_slam_msgs::LidarDisplayMsg_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vector_slam_msgs::LidarDisplayMsg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.timestamp);
    stream.next(m.robotLocX);
    stream.next(m.robotLocY);
    stream.next(m.robotAngle);
    stream.next(m.windowSize);
    stream.next(m.lines_p1x);
    stream.next(m.lines_p1y);
    stream.next(m.lines_p2x);
    stream.next(m.lines_p2y);
    stream.next(m.lines_col);
    stream.next(m.points_x);
    stream.next(m.points_y);
    stream.next(m.points_col);
    stream.next(m.circles_x);
    stream.next(m.circles_y);
    stream.next(m.circles_col);
    stream.next(m.text_x);
    stream.next(m.text_y);
    stream.next(m.text_col);
    stream.next(m.text);
    stream.next(m.text_height);
    stream.next(m.text_in_window_coords);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LidarDisplayMsg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vector_slam_msgs::LidarDisplayMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::vector_slam_msgs::LidarDisplayMsg_<ContainerAllocator> & v) 
  {
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "robotLocX: ";
    Printer<double>::stream(s, indent + "  ", v.robotLocX);
    s << indent << "robotLocY: ";
    Printer<double>::stream(s, indent + "  ", v.robotLocY);
    s << indent << "robotAngle: ";
    Printer<double>::stream(s, indent + "  ", v.robotAngle);
    s << indent << "windowSize: ";
    Printer<double>::stream(s, indent + "  ", v.windowSize);
    s << indent << "lines_p1x[]" << std::endl;
    for (size_t i = 0; i < v.lines_p1x.size(); ++i)
    {
      s << indent << "  lines_p1x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.lines_p1x[i]);
    }
    s << indent << "lines_p1y[]" << std::endl;
    for (size_t i = 0; i < v.lines_p1y.size(); ++i)
    {
      s << indent << "  lines_p1y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.lines_p1y[i]);
    }
    s << indent << "lines_p2x[]" << std::endl;
    for (size_t i = 0; i < v.lines_p2x.size(); ++i)
    {
      s << indent << "  lines_p2x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.lines_p2x[i]);
    }
    s << indent << "lines_p2y[]" << std::endl;
    for (size_t i = 0; i < v.lines_p2y.size(); ++i)
    {
      s << indent << "  lines_p2y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.lines_p2y[i]);
    }
    s << indent << "lines_col[]" << std::endl;
    for (size_t i = 0; i < v.lines_col.size(); ++i)
    {
      s << indent << "  lines_col[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.lines_col[i]);
    }
    s << indent << "points_x[]" << std::endl;
    for (size_t i = 0; i < v.points_x.size(); ++i)
    {
      s << indent << "  points_x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.points_x[i]);
    }
    s << indent << "points_y[]" << std::endl;
    for (size_t i = 0; i < v.points_y.size(); ++i)
    {
      s << indent << "  points_y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.points_y[i]);
    }
    s << indent << "points_col[]" << std::endl;
    for (size_t i = 0; i < v.points_col.size(); ++i)
    {
      s << indent << "  points_col[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.points_col[i]);
    }
    s << indent << "circles_x[]" << std::endl;
    for (size_t i = 0; i < v.circles_x.size(); ++i)
    {
      s << indent << "  circles_x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.circles_x[i]);
    }
    s << indent << "circles_y[]" << std::endl;
    for (size_t i = 0; i < v.circles_y.size(); ++i)
    {
      s << indent << "  circles_y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.circles_y[i]);
    }
    s << indent << "circles_col[]" << std::endl;
    for (size_t i = 0; i < v.circles_col.size(); ++i)
    {
      s << indent << "  circles_col[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.circles_col[i]);
    }
    s << indent << "text_x[]" << std::endl;
    for (size_t i = 0; i < v.text_x.size(); ++i)
    {
      s << indent << "  text_x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.text_x[i]);
    }
    s << indent << "text_y[]" << std::endl;
    for (size_t i = 0; i < v.text_y.size(); ++i)
    {
      s << indent << "  text_y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.text_y[i]);
    }
    s << indent << "text_col[]" << std::endl;
    for (size_t i = 0; i < v.text_col.size(); ++i)
    {
      s << indent << "  text_col[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.text_col[i]);
    }
    s << indent << "text[]" << std::endl;
    for (size_t i = 0; i < v.text.size(); ++i)
    {
      s << indent << "  text[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text[i]);
    }
    s << indent << "text_height[]" << std::endl;
    for (size_t i = 0; i < v.text_height.size(); ++i)
    {
      s << indent << "  text_height[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.text_height[i]);
    }
    s << indent << "text_in_window_coords[]" << std::endl;
    for (size_t i = 0; i < v.text_in_window_coords.size(); ++i)
    {
      s << indent << "  text_in_window_coords[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.text_in_window_coords[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // VECTOR_SLAM_MSGS_MESSAGE_LIDARDISPLAYMSG_H

