"""autogenerated by genpy from vector_slam_msgs/GuiMouseClickEvent.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class GuiMouseClickEvent(genpy.Message):
  _md5sum = "024d093145787d5820945b81ee2e9ed4"
  _type = "vector_slam_msgs/GuiMouseClickEvent"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """# Feedback in terms of mouse clicks on the localization GUI.
#

# Standard header. The frame should normally be "map", since the localization
# GUI reports coordinates in the world (map) frame.
std_msgs/Header header

# The 2D location where the "MouseDown" event occurred. The z coordinate of the
# Point32 should be set to 0 by publishers, and ignored by subscribers.
geometry_msgs/Point32 mouse_down

# The 2D location where the "MouseUp" event occurred. The z coordinate of the
# Point32 should be set to 0 by publishers, and ignored by subscribers.
geometry_msgs/Point32 mouse_up

# Binary mask of keyboard modifiers that were active when the mouse event occurred.
# 0x01 = Alt key  modifier
# 0x02 = Ctrl key modifier
# 0x04 = Shift key modifier
uint32 modifiers


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z
"""
  __slots__ = ['header','mouse_down','mouse_up','modifiers']
  _slot_types = ['std_msgs/Header','geometry_msgs/Point32','geometry_msgs/Point32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,mouse_down,mouse_up,modifiers

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GuiMouseClickEvent, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.mouse_down is None:
        self.mouse_down = geometry_msgs.msg.Point32()
      if self.mouse_up is None:
        self.mouse_up = geometry_msgs.msg.Point32()
      if self.modifiers is None:
        self.modifiers = 0
    else:
      self.header = std_msgs.msg.Header()
      self.mouse_down = geometry_msgs.msg.Point32()
      self.mouse_up = geometry_msgs.msg.Point32()
      self.modifiers = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_6fI.pack(_x.mouse_down.x, _x.mouse_down.y, _x.mouse_down.z, _x.mouse_up.x, _x.mouse_up.y, _x.mouse_up.z, _x.modifiers))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.mouse_down is None:
        self.mouse_down = geometry_msgs.msg.Point32()
      if self.mouse_up is None:
        self.mouse_up = geometry_msgs.msg.Point32()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.mouse_down.x, _x.mouse_down.y, _x.mouse_down.z, _x.mouse_up.x, _x.mouse_up.y, _x.mouse_up.z, _x.modifiers,) = _struct_6fI.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_6fI.pack(_x.mouse_down.x, _x.mouse_down.y, _x.mouse_down.z, _x.mouse_up.x, _x.mouse_up.y, _x.mouse_up.z, _x.modifiers))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.mouse_down is None:
        self.mouse_down = geometry_msgs.msg.Point32()
      if self.mouse_up is None:
        self.mouse_up = geometry_msgs.msg.Point32()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.mouse_down.x, _x.mouse_down.y, _x.mouse_down.z, _x.mouse_up.x, _x.mouse_up.y, _x.mouse_up.z, _x.modifiers,) = _struct_6fI.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_6fI = struct.Struct("<6fI")
